spring.application.name=tradingview-webhook

dhan.client-id=1103827341
dhan.access-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzc3MzY4NDEzLCJpYXQiOjE3NzcyODIwMTMsInRva2VuQ29uc3VtZXJUeXBlIjoiU0VMRiIsIndlYmhvb2tVcmwiOiIiLCJkaGFuQ2xpZW50SWQiOiIxMTAzODI3MzQxIn0.Bde4o5PTCMvutiDFF08VPfYb7qkZv9B4ZycnQ04pYGV3_RihIWoVlTgDBCWtR3ORMJDOyDQ4CTHCfrTNli1o5Q

spring.datasource.url=jdbc:postgresql://metro.proxy.rlwy.net:43193/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=HVUkGHTjHwpUYbqKAbRdAEQYrhmzdnGB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=5432
