spring.application.name=tradingview-webhook

dhan.client-id=1103827341
dhan.access-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzU2ODE1MzEyLCJ0b2tlbkNvbnN1bWVyVHlwZSI6IlNFTEYiLCJ3ZWJob29rVXJsIjoiIiwiZGhhbkNsaWVudElkIjoiMTEwMzgyNzM0MSJ9.CdGRxOOwqqhfYk0MTxz1bsoIevrgXyyTAx13_OYLvuT5qMtbJijEUi8k-KqsoVyYjaHBp4l8SUkxW8-6LvTFTg

spring.datasource.url=jdbc:postgresql://metro.proxy.rlwy.net:43193/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=HVUkGHTjHwpUYbqKAbRdAEQYrhmzdnGB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=5432
