spring.application.name=tradingview-webhook

dhan.client-id=1107433698
dhan.access-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzc3Mzk0OTYxLCJpYXQiOjE3NzczMDg1NjEsInRva2VuQ29uc3VtZXJUeXBlIjoiU0VMRiIsIndlYmhvb2tVcmwiOiIiLCJkaGFuQ2xpZW50SWQiOiIxMTA3NDMzNjk4In0.Rf5SeGeQheyKRpuCWAIwnIWeii1jY3Gmgl_nsuOfLk-OkMxUOAgNYNebLIr1hVxNmdI959U3PygLHNghnzGjxQ

spring.datasource.url=jdbc:postgresql://metro.proxy.rlwy.net:43193/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=HVUkGHTjHwpUYbqKAbRdAEQYrhmzdnGB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=5432
